plugins:
  chord_directory_enabled:
    default: false
  chord_directory_interval_number:
    default: 1
  chord_directory_interval_type:
    enum: "ChordDirectory::IntervalOptions"
    default: days
  chord_directory_ucfs:
    default: "Ask Me About"
